pokemons = [
    {'nome': 'Bulbasaur', 'tipo': 'grama', 'ataque': 49, 'defesa': 49, 'hp': 45},
    {'nome': 'Ivysaur', 'tipo': 'grama', 'ataque': 62, 'defesa': 63, 'hp': 60},
    {'nome': 'Venusaur', 'tipo': 'grama', 'ataque': 82, 'defesa': 83, 'hp': 80},
    {'nome': 'Charmander', 'tipo': 'fogo', 'ataque': 52, 'defesa': 43, 'hp': 39},
    {'nome': 'Charmeleon', 'tipo': 'fogo', 'ataque': 64, 'defesa': 58, 'hp': 58},
    {'nome': 'Charizard', 'tipo': 'fogo', 'ataque': 84, 'defesa': 78, 'hp': 78},
    {'nome': 'Squirtle', 'tipo': 'agua', 'ataque': 48, 'defesa': 65, 'hp': 44},
    {'nome': 'Wartortle', 'tipo': 'agua', 'ataque': 63, 'defesa': 80, 'hp': 59},
    {'nome': 'Blastoise', 'tipo': 'agua', 'ataque': 83, 'defesa': 100, 'hp': 79},
    {'nome': 'Caterpie', 'tipo': 'inseto', 'ataque': 30, 'defesa': 35, 'hp': 45},
    {'nome': 'Metapod', 'tipo': 'inseto', 'ataque': 20, 'defesa': 55, 'hp': 50},
    {'nome': 'Butterfree', 'tipo': 'inseto', 'ataque': 45, 'defesa': 50, 'hp': 60},
    {'nome': 'Weedle', 'tipo': 'inseto', 'ataque': 35, 'defesa': 30, 'hp': 40},
    {'nome': 'Kakuna', 'tipo': 'inseto', 'ataque': 25, 'defesa': 50, 'hp': 45},
    {'nome': 'Beedrill', 'tipo': 'inseto', 'ataque': 90, 'defesa': 40, 'hp': 65},
    {'nome': 'Pidgey', 'tipo': 'normal', 'ataque': 45, 'defesa': 40, 'hp': 40},
    {'nome': 'Pidgeotto', 'tipo': 'normal', 'ataque': 60, 'defesa': 55, 'hp': 63},
    {'nome': 'Pidgeot', 'tipo': 'normal', 'ataque': 80, 'defesa': 75, 'hp': 83},
    {'nome': 'Rattata', 'tipo': 'normal', 'ataque': 56, 'defesa': 35, 'hp': 30},
    {'nome': 'Raticate', 'tipo': 'normal', 'ataque': 81, 'defesa': 60, 'hp': 55},
    {'nome': 'Spearow', 'tipo': 'normal', 'ataque': 60, 'defesa': 30, 'hp': 40},
    {'nome': 'Fearow', 'tipo': 'normal', 'ataque': 90, 'defesa': 65, 'hp': 65},
    {'nome': 'Ekans', 'tipo': 'venenoso', 'ataque': 60, 'defesa': 44, 'hp': 35},
    {'nome': 'Arbok', 'tipo': 'venenoso', 'ataque': 85, 'defesa': 69, 'hp': 60},
    {'nome': 'Pikachu', 'tipo': 'eletrico', 'ataque': 55, 'defesa': 40, 'hp': 35},
    {'nome': 'Raichu', 'tipo': 'eletrico', 'ataque': 90, 'defesa': 55, 'hp': 60},
    {'nome': 'Sandshrew', 'tipo': 'normal', 'ataque': 75, 'defesa': 85, 'hp': 50},
    {'nome': 'Sandslash', 'tipo': 'normal', 'ataque': 100, 'defesa': 110, 'hp': 75},
    {'nome': 'Nidoran♀', 'tipo': 'venenoso', 'ataque': 47, 'defesa': 52, 'hp': 55},
    {'nome': 'Nidorina', 'tipo': 'venenoso', 'ataque': 62, 'defesa': 67, 'hp': 70},
    {'nome': 'Nidoqueen', 'tipo': 'venenoso',
        'ataque': 92, 'defesa': 87, 'hp': 90},
    {'nome': 'Nidoran♂', 'tipo': 'venenoso', 'ataque': 57, 'defesa': 40, 'hp': 46},
    {'nome': 'Nidorino', 'tipo': 'venenoso', 'ataque': 72, 'defesa': 57, 'hp': 61},
    {'nome': 'Nidoking', 'tipo': 'venenoso',
        'ataque': 102, 'defesa': 77, 'hp': 81},
    {'nome': 'Clefairy', 'tipo': 'normal', 'ataque': 45, 'defesa': 48, 'hp': 35},
    {'nome': 'Clefable', 'tipo': 'normal', 'ataque': 70, 'defesa': 73, 'hp': 60},
    {'nome': 'Vulpix', 'tipo': 'fogo', 'ataque': 41, 'defesa': 40, 'hp': 38},
    {'nome': 'Ninetales', 'tipo': 'fogo', 'ataque': 76, 'defesa': 75, 'hp': 73},
    {'nome': 'Jigglypuff', 'tipo': 'normal',
        'ataque': 45, 'defesa': 20, 'hp': 115},
    {'nome': 'Wigglytuff', 'tipo': 'normal',
        'ataque': 70, 'defesa': 45, 'hp': 140},
    {'nome': 'Zubat', 'tipo': 'venenoso', 'ataque': 45, 'defesa': 35, 'hp': 40},
    {'nome': 'Golbat', 'tipo': 'venenoso', 'ataque': 80, 'defesa': 70, 'hp': 75},
    {'nome': 'Oddish', 'tipo': 'grama', 'ataque': 50, 'defesa': 55, 'hp': 45},
    {'nome': 'Gloom', 'tipo': 'grama', 'ataque': 65, 'defesa': 70, 'hp': 60},
    {'nome': 'Vileplume', 'tipo': 'grama', 'ataque': 80, 'defesa': 85, 'hp': 75},
    {'nome': 'Paras', 'tipo': 'inseto', 'ataque': 70, 'defesa': 55, 'hp': 50},
    {'nome': 'Parasect', 'tipo': 'inseto', 'ataque': 95, 'defesa': 80, 'hp': 75},
    {'nome': 'Venonat', 'tipo': 'inseto', 'ataque': 55, 'defesa': 50, 'hp': 45},
    {'nome': 'Venomoth', 'tipo': 'inseto', 'ataque': 70, 'defesa': 65, 'hp': 60},
    {'nome': 'Diglett', 'tipo': 'normal', 'ataque': 55, 'defesa': 25, 'hp': 10},
    {'nome': 'Dugtrio', 'tipo': 'normal', 'ataque': 80, 'defesa': 50, 'hp': 35},
    {'nome': 'Meowth', 'tipo': 'normal', 'ataque': 45, 'defesa': 35, 'hp': 40},
    {'nome': 'Persian', 'tipo': 'normal', 'ataque': 70, 'defesa': 60, 'hp': 65},
    {'nome': 'Psyduck', 'tipo': 'agua', 'ataque': 52, 'defesa': 48, 'hp': 50},
    {'nome': 'Golduck', 'tipo': 'agua', 'ataque': 82, 'defesa': 78, 'hp': 80},
    {'nome': 'Mankey', 'tipo': 'normal', 'ataque': 80, 'defesa': 35, 'hp': 40},
    {'nome': 'Primeape', 'tipo': 'normal', 'ataque': 105, 'defesa': 60, 'hp': 65},
    {'nome': 'Growlithe', 'tipo': 'fogo', 'ataque': 70, 'defesa': 45, 'hp': 55},
    {'nome': 'Arcanine', 'tipo': 'fogo', 'ataque': 110, 'defesa': 80, 'hp': 90},
    {'nome': 'Poliwag', 'tipo': 'agua', 'ataque': 50, 'defesa': 40, 'hp': 40},
    {'nome': 'Poliwhirl', 'tipo': 'agua', 'ataque': 65, 'defesa': 65, 'hp': 65},
    {'nome': 'Poliwrath', 'tipo': 'agua', 'ataque': 90, 'defesa': 95, 'hp': 90},
    {'nome': 'Abra', 'tipo': 'psiquico', 'ataque': 20, 'defesa': 15, 'hp': 20},
    {'nome': 'Kadabra', 'tipo': 'psiquico', 'ataque': 35, 'defesa': 30, 'hp': 35},
    {'nome': 'Alakazam', 'tipo': 'psiquico', 'ataque': 50, 'defesa': 45, 'hp': 55},
    {'nome': 'Machop', 'tipo': 'normal', 'ataque': 80, 'defesa': 50, 'hp': 70},
    {'nome': 'Machoke', 'tipo': 'normal', 'ataque': 100, 'defesa': 70, 'hp': 80},
    {'nome': 'Machamp', 'tipo': 'normal', 'ataque': 130, 'defesa': 80, 'hp': 90},
    {'nome': 'Bellsprout', 'tipo': 'grama', 'ataque': 75, 'defesa': 35, 'hp': 40},
    {'nome': 'Weepinbell', 'tipo': 'grama', 'ataque': 90, 'defesa': 50, 'hp': 55},
    {'nome': 'Victreebel', 'tipo': 'grama', 'ataque': 105, 'defesa': 65, 'hp': 70},
    {'nome': 'Tentacool', 'tipo': 'agua', 'ataque': 40, 'defesa': 35, 'hp': 40},
    {'nome': 'Tentacruel', 'tipo': 'agua', 'ataque': 70, 'defesa': 65, 'hp': 80},
    {'nome': 'Geodude', 'tipo': 'normal', 'ataque': 80, 'defesa': 100, 'hp': 40},
    {'nome': 'Graveler', 'tipo': 'normal', 'ataque': 105, 'defesa': 115, 'hp': 55},
    {'nome': 'Golem', 'tipo': 'normal', 'ataque': 130, 'defesa': 145, 'hp': 80},
    {'nome': 'Ponyta', 'tipo': 'fogo', 'ataque': 85, 'defesa': 55, 'hp': 50},
    {'nome': 'Rapidash', 'tipo': 'fogo', 'ataque': 100, 'defesa': 70, 'hp': 65},
    {'nome': 'Slowpoke', 'tipo': 'agua', 'ataque': 65, 'defesa': 65, 'hp': 90},
    {'nome': 'Slowbro', 'tipo': 'agua', 'ataque': 75, 'defesa': 110, 'hp': 80},
    {'nome': 'Magnemite', 'tipo': 'eletrico',
        'ataque': 35, 'defesa': 70, 'hp': 25},
    {'nome': 'Magneton', 'tipo': 'eletrico', 'ataque': 60, 'defesa': 95, 'hp': 50},
    {'nome': 'Farfetchd', 'tipo': 'normal', 'ataque': 65, 'defesa': 55, 'hp': 52},
    {'nome': 'Doduo', 'tipo': 'normal', 'ataque': 85, 'defesa': 45, 'hp': 35},
    {'nome': 'Dodrio', 'tipo': 'normal', 'ataque': 110, 'defesa': 70, 'hp': 60},
    {'nome': 'Seel', 'tipo': 'agua', 'ataque': 45, 'defesa': 55, 'hp': 45},
    {'nome': 'Dewgong', 'tipo': 'agua', 'ataque': 70, 'defesa': 80, 'hp': 70},
    {'nome': 'Grimer', 'tipo': 'venenoso', 'ataque': 80, 'defesa': 50, 'hp': 40},
    {'nome': 'Muk', 'tipo': 'venenoso', 'ataque': 105, 'defesa': 75, 'hp': 65},
    {'nome': 'Shellder', 'tipo': 'agua', 'ataque': 65, 'defesa': 100, 'hp': 30},
    {'nome': 'Cloyster', 'tipo': 'agua', 'ataque': 95, 'defesa': 180, 'hp': 50},
    {'nome': 'Gastly', 'tipo': 'fantasma', 'ataque': 30, 'defesa': 35, 'hp': 30},
    {'nome': 'Haunter', 'tipo': 'fantasma', 'ataque': 45, 'defesa': 50, 'hp': 45},
    {'nome': 'Gengar', 'tipo': 'fantasma', 'ataque': 60, 'defesa': 65, 'hp': 60},
    {'nome': 'Onix', 'tipo': 'normal', 'ataque': 45, 'defesa': 160, 'hp': 70},
    {'nome': 'Drowzee', 'tipo': 'psiquico', 'ataque': 48, 'defesa': 45, 'hp': 60},
    {'nome': 'Drowzee', 'tipo': 'psiquico', 'ataque': 48, 'defesa': 45, 'hp': 60},
    {'nome': 'Hypno', 'tipo': 'psiquico', 'ataque': 73, 'defesa': 70, 'hp': 85},
    {'nome': 'Krabby', 'tipo': 'agua', 'ataque': 105, 'defesa': 90, 'hp': 30},
    {'nome': 'Kingler', 'tipo': 'agua', 'ataque': 130, 'defesa': 115, 'hp': 55},
    {'nome': 'Voltorb', 'tipo': 'eletrico', 'ataque': 30, 'defesa': 50, 'hp': 40},
    {'nome': 'Electrode', 'tipo': 'eletrico',
        'ataque': 50, 'defesa': 70, 'hp': 60},
    {'nome': 'Exeggcute', 'tipo': 'grama', 'ataque': 40, 'defesa': 80, 'hp': 60},
    {'nome': 'Exeggutor', 'tipo': 'grama', 'ataque': 95, 'defesa': 85, 'hp': 95},
    {'nome': 'Cubone', 'tipo': 'normal', 'ataque': 50, 'defesa': 95, 'hp': 35},
    {'nome': 'Marowak', 'tipo': 'normal', 'ataque': 80, 'defesa': 110, 'hp': 45},
    {'nome': 'Hitmonlee', 'tipo': 'normal', 'ataque': 120, 'defesa': 53, 'hp': 87},
    {'nome': 'Hitmonchan', 'tipo': 'normal',
        'ataque': 105, 'defesa': 79, 'hp': 76},
    {'nome': 'Lickitung', 'tipo': 'normal', 'ataque': 55, 'defesa': 75, 'hp': 90},
    {'nome': 'Koffing', 'tipo': 'venenoso', 'ataque': 65, 'defesa': 95, 'hp': 40},
    {'nome': 'Weezing', 'tipo': 'venenoso', 'ataque': 90, 'defesa': 120, 'hp': 65},
    {'nome': 'Rhyhorn', 'tipo': 'normal', 'ataque': 85, 'defesa': 95, 'hp': 30},
    {'nome': 'Rhydon', 'tipo': 'normal', 'ataque': 130, 'defesa': 120, 'hp': 60},
    {'nome': 'Chansey', 'tipo': 'normal', 'ataque': 5, 'defesa': 5, 'hp': 250},
    {'nome': 'Tangela', 'tipo': 'grama', 'ataque': 55, 'defesa': 115, 'hp': 60},
    {'nome': 'Kangaskhan', 'tipo': 'normal', 'ataque': 95, 'defesa': 80, 'hp': 90},
    {'nome': 'Horsea', 'tipo': 'agua', 'ataque': 40, 'defesa': 70, 'hp': 30},
    {'nome': 'Seadra', 'tipo': 'agua', 'ataque': 65, 'defesa': 95, 'hp': 55},
    {'nome': 'Goldeen', 'tipo': 'agua', 'ataque': 67, 'defesa': 60, 'hp': 45},
    {'nome': 'Seaking', 'tipo': 'agua', 'ataque': 92, 'defesa': 65, 'hp': 80},
    {'nome': 'Staryu', 'tipo': 'agua', 'ataque': 45, 'defesa': 55, 'hp': 40},
    {'nome': 'Starmie', 'tipo': 'agua', 'ataque': 60, 'defesa': 75, 'hp': 55},
    {'nome': 'Mr. Mime', 'tipo': 'psiquico', 'ataque': 45, 'defesa': 65, 'hp': 40},
    {'nome': 'Scyther', 'tipo': 'inseto', 'ataque': 110, 'defesa': 80, 'hp': 70},
    {'nome': 'Jynx', 'tipo': 'psiquico', 'ataque': 50, 'defesa': 35, 'hp': 95},
    {'nome': 'Electabuzz', 'tipo': 'eletrico',
        'ataque': 83, 'defesa': 57, 'hp': 105},
    {'nome': 'Magmar', 'tipo': 'fogo', 'ataque': 95, 'defesa': 57, 'hp': 93},
    {'nome': 'Pinsir', 'tipo': 'inseto', 'ataque': 125, 'defesa': 100, 'hp': 85},
    {'nome': 'Tauros', 'tipo': 'normal', 'ataque': 100, 'defesa': 95, 'hp': 70},
    {'nome': 'Magikarp', 'tipo': 'agua', 'ataque': 10, 'defesa': 55, 'hp': 20},
    {'nome': 'Gyarados', 'tipo': 'agua', 'ataque': 125, 'defesa': 79, 'hp': 100},
    {'nome': 'Lapras', 'tipo': 'agua', 'ataque': 85, 'defesa': 80, 'hp': 130},
    {'nome': 'Ditto', 'tipo': 'normal', 'ataque': 48, 'defesa': 48, 'hp': 48},
    {'nome': 'Eevee', 'tipo': 'normal', 'ataque': 55, 'defesa': 50, 'hp': 55},
    {'nome': 'Vaporeon', 'tipo': 'agua', 'ataque': 65, 'defesa': 60, 'hp': 65},
    {'nome': 'Jolteon', 'tipo': 'eletrico', 'ataque': 65, 'defesa': 60, 'hp': 65},
    {'nome': 'Flareon', 'tipo': 'fogo', 'ataque': 130, 'defesa': 60, 'hp': 65},
    {'nome': 'Porygon', 'tipo': 'normal', 'ataque': 60, 'defesa': 70, 'hp': 40},
    {'nome': 'Omanyte', 'tipo': 'agua', 'ataque': 40, 'defesa': 100, 'hp': 35},
    {'nome': 'Omastar', 'tipo': 'agua', 'ataque': 60, 'defesa': 125, 'hp': 55},
    {'nome': 'Kabuto', 'tipo': 'agua', 'ataque': 80, 'defesa': 90, 'hp': 30},
    {'nome': 'Kabutops', 'tipo': 'agua', 'ataque': 115, 'defesa': 105, 'hp': 65},
    {'nome': 'Aerodactyl', 'tipo': 'normal',
        'ataque': 105, 'defesa': 65, 'hp': 80},
    {'nome': 'Snorlax', 'tipo': 'normal', 'ataque': 110, 'defesa': 65, 'hp': 160},
    {'nome': 'Articuno', 'tipo': 'agua', 'ataque': 85, 'defesa': 100, 'hp': 90},
    {'nome': 'Zapdos', 'tipo': 'eletrico', 'ataque': 90, 'defesa': 85, 'hp': 90},
    {'nome': 'Moltres', 'tipo': 'fogo', 'ataque': 100, 'defesa': 90, 'hp': 90},
    {'nome': 'Dratini', 'tipo': 'agua', 'ataque': 64, 'defesa': 45, 'hp': 41},
    {'nome': 'Dragonair', 'tipo': 'agua', 'ataque': 84, 'defesa': 65, 'hp': 61},
    {'nome': 'Dragonite', 'tipo': 'agua', 'ataque': 134, 'defesa': 95, 'hp': 81},
    {'nome': 'Mewtwo', 'tipo': 'psiquico', 'ataque': 110, 'defesa': 90, 'hp': 106},
    {'nome': 'Mew', 'tipo': 'psiquico', 'ataque': 100, 'defesa': 100, 'hp': 100}]
